### ISSUE TITLE
Emit events for link definitions

### ISSUE THREAD

**Issue by hellux** [hellux/jotdown#14]
Currently, link definitions are only used to resolve links and are then ignored. However, the position of link definitions may be useful to a consumer, e.g. for a pretty-printer. If we also want to let consumers resolve links it would become required emit them.

Would need to

- not ignore link definitions in Parser::block, add and emit link definition Event
- ignore link definitions for html output, using html::FilteredEvents

**Comment by kaj** [comment]
I also would like `SpanLinkType::Reference` to contain the (unresolved) reference (or for `Container::Link` to contain it some other way).

My reason is that I would like to handle some (locally defined) automatic reference.  For exemple, I would like the document `[Some word][wp]` to render as a `<a href="https://en.wikipedia.org/wiki/Some+word" title="Some word (in wikipedia)">Some word</a>`.

**Comment by hellux** [comment]
> My reason is that I would like to handle some (locally defined)
> automatic reference.  For exemple, I would like the document
> `[Some word][wp]` to render as a
> `<a> href="https://en.wikipedia.org/wiki/Some+word" title="Some word (in wikipedia)">Some word</a>`.

I think this is something that we wish to be able to support.

> I also would like `SpanLinkType::Reference` to contain the
> (unresolved) reference.

It would be possible to always provide the reference link, regardless if
it is unresolved or not, but that may increase the size of Event (which
may or may not be very important) because I think the links already are
the biggest variants in the enum.

> or for `Container::Link` to contain it some other way

We have been considering moving to a single-pass parser, which would
require us to represent unresolved links (letting user optionally
perform multiple passes to resolve links). We could maybe add this to
the Event type already now, and use it for reference events that do not
have a matching link definition.

---

A different approach is to use a callback function that is called when
unresolved links are encountered. I don't think there is any benefit to
this, though. pulldown_cmark does this but I think it is because
Markdown must know whether the inline link is valid or not in order to
parse it correctly.

---

I'm leaning towards adding an unresolved variant, but perhaps also worth
exploring always keeping the reference.

**Comment by kaj** [comment]
One way of handling this, that shouldn't make `Event` any bigger, is to add a variant `SpanLinkType::Unresolved` (to the existing `Inline` and `Reference`), and in that case let the `url` in `Container::Link(url, type)` be the unresolved string.

Than an automatic link handler could match for that, calculate the actual url, and replace the `Container::Link(refstr, LinkType::Span(Unresolved))` with `Container::Link(actual_url, LinkType::Span(Reference))`. Note that for my use-case, I would need to handle the _content_ of the link container to calculate the actual url (and possibly other attributes (e.g. title or hreflang), so this would be a lot easier given the AST suggested in #17 .

**Comment by hellux** [comment]
> One way of handling this, that shouldn't make `Event` any bigger, is
> to add a variant `SpanLinkType::Unresolved` (to the existing `Inline`
> and `Reference`), and in that case let the `url` in
> `Container::Link(url, type)` be the unresolved string.

Yes, something like that was what I had in mind. I'm guessing it is very
rare to need both the tag and the resolved URL. I think we should go
ahead with this as we will need it anyway for a single-pass parser. Also
makes it possible to detect unresolved links, e.g. for erroring out.

> Note that for my use-case, I would need to handle the _content_ of the
> link container to calculate the actual url (and possibly other
> attributes (e.g. title or hreflang), so this would be a lot easier
> given the AST suggested in #17 .

Yeah, this is a drawback when dealing with events directly, it is quite
inconvenient to collect the content.

---

Another option, that might be more by design, is to use a span with a
class: `[Some word]{.wp}`. A benefit of `[Some word][wp]` is that it
indicates that it is a link, but it might be confusing as it looks a
normal reference link.

Also, if the unresolved tag is available in the Event, then if you were
to use `[Some word][]{.wp}`, the content would be placed in the `url` as
the tag.

Both of `[Some word][wp]` and `[Some word][]{.wp}` have the risk of
colliding with existing link definitions, though. `[Some word](){.wp}`
could also be an option, and doesn't have this problem.
