### ISSUE TITLE
Source positions

### ISSUE THREAD

**Issue by hellux** [hellux/jotdown#3]
Currently, source positions are not available for events. However, they are very useful and we should be able to implement this.

pulldown-cmark has a iter_with_offsets method on the Parser that gives an iterator of tuples that contain both an event and a start/end position. We could do something similar.

**Comment by kmaasrud** [comment]
Would it be possible to do this with the `Span`s used throughout the code? Or perhaps by expanding the `DiscontinuousString` trait to get the source range?

**Comment by hellux** [comment]
> Would it be possible to do this with the `Span`s used throughout the
> code?
Yes, but they might not be complete.

They are set in order to allow extraction of only necessary data, e.g.
the span of block::Leaf::CodeBlock is the only language specifier / info
string after the fence. So the location of the actual fences are lost.

It is done similarly for some inline events, e.g. the autolink span is
only the URL itself, without the `<` and `>`. In this case, we know
there will always be exact one opener and closer before and after so
technically, no information is lost here. However, e.g. the raw inline
format has the span set to format specifier, so the span of the openers
and closers is lost I think.

So I think we need to store more information in the block and inline
events.

> Or perhaps by expanding the `DiscontinuousString` trait to get the
> source range?
The `DiscontinuousString` is currently completely removed on the
inline_perf branch as it imposed some limitations (required whole block
to be parsed before inline parsing began) and was problematic for
performance (was big and had to be cloned for peeking during lexing).
But it should be possible to get the ranges now also.

**Comment by hellux** [comment]
For container attributes, do we want the start/end events to only
include the start/end delimiters or do we want to them to include the
whole container element?

E.g. should `_abc_` be

```
start emph "_"
str "abc"
end emph "_"
```

or

```
start emph "_abc_"
str "abc"
end emph "_abc_"
```

If we go with the latter, we would be required to buffer from the start
event until we have parsed the end event.

If we choose the former, how should links be represented? E.g.
`[text](url)`:

```
start inline_link url=url "["
str "text"
end inline_link "](url)"
```

**Comment by kmaasrud** [comment]
I'd say the former makes a lot more sense for end-use cases, e.g. highlighting. Avoiding any performance hits as much as possible also makes sense for such an API, as user who need  more complex syntax knowledge would probably rather just use a whole AST
