### ISSUE TITLE
Attributes are parsed inside math

### ISSUE THREAD

**Issue by kmaasrud** [hellux/jotdown#41]
When writing something like `\sum_{j=0}` in a math environment, the `{j=0}` part is interpreted by the parser as an attribute. This leads to it being removed from the rendered TeX math. Everything inside a math environment should be parsed verbatim.

**Comment by kmaasrud** [comment]
Added info: The issue is easily avoided by adding spaces, e.g. `\sum_{j = 0}`.

**Comment by hellux** [comment]
Thanks, I pushed a fix to master. I will make a release soon so the fix
should be available shortly.
