### ISSUE TITLE
Surface unordered list style?

### ISSUE THREAD

**Issue by kosayoda** [hellux/jotdown#57]
Hello!

I was wondering if the `jotdown` parser could surface the character used for a list item in an unordered list (`-`, `+`, and `*`). Currently, the style is swallowed for `ListKind::Unordered`:

https://github.com/hellux/jotdown/blob/6e6c28ed5a5944f237e13e4d41a091bf623f30ae/src/lib.rs#L2570-L2572

I understand that the `djot` specification only has `bullet` stated for all three, but I think the distinction could help with eg. a custom HTML renderer that uses a different `list-style-type`.

Thanks!

EDIT: `djot.js` does [include the bullet list style in its AST](https://github.com/jgm/djot.js/blob/cf97586a804949591e8584bf081b4ddfd70f09f5/src/ast.ts#L87-L95)

**Comment by hellux** [comment]
I think this is reasonable to have, we could add an extra enum here. It may also be useful for e.g. formatters.

**Comment by hellux** [comment]
Bullet type exposed in events as of release 0.6.0.
