### ISSUE TITLE
Add Pretty html?

### ISSUE THREAD

**Issue by dcampbell24** [hellux/jotdown#58]
Would it be hard to add support for pretty html?

**Comment by hellux** [comment]
What do you have in mind, exactly? The HTML output already includes newlines to make it more readable.

**Comment by dcampbell24** [comment]
Add the ability to specify tabs or number of spaces indent and starting indent.

**Comment by hellux** [comment]
here's a very simple implementation: #59, something like that?

**Comment by dcampbell24** [comment]
Yeah.

**Comment by hellux** [comment]
Indented HTML available as of release 0.6.0.
